name: Run template tests

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: "Pytesting"
        runs-on: ubuntu-latest  
        steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
          with:
            persist-credentials: false
            fetch-depth: 0
        - name: "Run tests"
          run: |
            run: python -m pip install --upgrade tox
            cd gmepack
            tox -e test

    # test:
#   test:
#     uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
#     with:
#       envs: |
#         - linux: test
